import datetime
import os
from typing import Any

from langchain_core.tools import tool
from pptx import Presentation
from pptx.util import Pt
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate


@tool
def generate_pdf_report(title: str, content: str, filename: str) -> str:
    """Create a structured, premium PDF report from a text/markdown string and save it.

    Args:
        title: The title of the PDF report.
        content: The text content with headers and paragraphs.
        filename: Target filename (e.g. 'summary_report.pdf').

    Returns:
        The absolute path to the generated PDF file.
    """
    try:
        uploads_dir = os.path.join(os.getcwd(), "uploads")
        os.makedirs(uploads_dir, exist_ok=True)
        file_path = os.path.join(uploads_dir, filename)

        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = getSampleStyleSheet()

        # Custom Premium Styles
        title_style = ParagraphStyle(
            name="ReportTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            textColor=colors.HexColor("#1E3A8A"),  # Navy blue
            spaceAfter=15,
        )

        meta_style = ParagraphStyle(
            name="ReportMeta",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#6B7280"),  # Grey
            spaceAfter=25,
        )

        h1_style = ParagraphStyle(
            name="ReportH1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#1E3A8A"),
            spaceBefore=15,
            spaceAfter=8,
            keepWithNext=True,
        )

        h2_style = ParagraphStyle(
            name="ReportH2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#10B981"),  # Emerald
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True,
        )

        body_style = ParagraphStyle(
            name="ReportBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1F2937"),  # Dark charcoal
            spaceAfter=10,
        )

        story = []

        # Add Title & Metadata
        story.append(Paragraph(title, title_style))
        current_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        story.append(
            Paragraph(
                f"Generated by Enterprise Research Platform  |  Date: {current_date}",
                meta_style,
            )
        )

        # Parse basic markdown structure from content
        paragraphs = content.split("\n\n")
        for para in paragraphs:
            para = para.strip()
            if not para:
                continue

            if para.startswith("# "):
                text = para[2:].strip()
                story.append(Paragraph(text, h1_style))
            elif para.startswith("## "):
                text = para[3:].strip()
                story.append(Paragraph(text, h2_style))
            elif para.startswith("### "):
                text = para[4:].strip()
                story.append(Paragraph(text, h2_style))
            else:
                # Replace inline markdown bold/italic tags if present
                clean_text = para.replace("**", "<b>").replace("__", "<b>")
                # Wait, we need to balance tags for safety
                story.append(Paragraph(clean_text, body_style))

        doc.build(story)
        return os.path.abspath(file_path)

    except Exception as e:
        return f"Error generating PDF: {e!s}"


@tool
def generate_pptx_report(
    title: str, slides_content: list[dict[str, Any]], filename: str
) -> str:
    """Create a structured PowerPoint presentation slide-deck and save it.

    Args:
        title: Title of the presentation (Slide 1 title).
        slides_content: List of dictionaries representing slides, e.g.:
                       [{"title": "Introduction", "bullets": ["Point A", "Point B"]}]
        filename: Target filename (e.g. 'summary_deck.pptx').

    Returns:
        The absolute path to the generated PPTX file.
    """
    try:
        uploads_dir = os.path.join(os.getcwd(), "uploads")
        os.makedirs(uploads_dir, exist_ok=True)
        file_path = os.path.join(uploads_dir, filename)

        prs = Presentation()

        # Add Title Slide (Layout 0)
        slide_layout_title = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout_title)
        slide.shapes.title.text = title
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated Report presentation"

        # Add Content Slides (Layout 1: Title and Content)
        slide_layout_content = prs.slide_layouts[1]
        for slide_data in slides_content:
            slide_title = slide_data.get("title", "Slide")
            bullets = slide_data.get("bullets", [])

            slide = prs.slides.add_slide(slide_layout_content)
            slide.shapes.title.text = slide_title

            if len(slide.placeholders) > 1 and bullets:
                tf = slide.placeholders[1].text_frame
                # Clear placeholder default paragraphs
                tf.text = ""
                for idx, bullet_text in enumerate(bullets):
                    if idx == 0:
                        p = tf.paragraphs[0]
                        p.text = bullet_text
                    else:
                        p = tf.add_paragraph()
                        p.text = bullet_text
                        p.level = 0
                    p.font.size = Pt(18)

        prs.save(file_path)
        return os.path.abspath(file_path)

    except Exception as e:
        return f"Error generating PowerPoint: {e!s}"
