"""add_document_checksum

Revision ID: 0101ae028342
Revises: bbe918fc014c
Create Date: 2026-07-12 21:31:44.810699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0101ae028342"
down_revision: str | Sequence[str] | None = "bbe918fc014c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("checksum", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint("uq_documents_checksum", "documents", ["checksum"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_checksum", "documents", type_="unique")
    op.drop_column("documents", "checksum")
    # ### end Alembic commands ###
