"""add_is_active_to_training_jobs

Revision ID: 2cda3016267e
Revises: 0101ae028342
Create Date: 2026-07-14 18:06:43.016096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cda3016267e'
down_revision: Union[str, Sequence[str], None] = '0101ae028342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langgraph_checkpoint_blobs',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('blob_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version')
    )
    op.create_table('langgraph_checkpoint_writes',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('blob_data', sa.LargeBinary(), nullable=False),
    sa.Column('task_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('langgraph_checkpoints',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_data', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.add_column('training_jobs', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'is_active')
    op.drop_table('langgraph_checkpoints')
    op.drop_table('langgraph_checkpoint_writes')
    op.drop_table('langgraph_checkpoint_blobs')
    # ### end Alembic commands ###
